kafka:
  broker: localhost:9092
  schema_registry: http://localhost:8081
  topics:
    weather: weather_data
    lowTemp: low-temp
    highTemp: high_temp
    strongWind: stong_wind
  defaultTopicNumPartitions: 1
  defaultTopicReplicationFactor: 1