version: '2'

services:

  weather-data-producer:
    image: weather-data-producer-v1
    ports:
      - "10001:8080"
    depends_on:
      - kafka-cluster

  weather-data-processor:
    image: weather-data-processor-v1
    ports:
      - "10002:8080"
    depends_on:
      - kafka-cluster

  kafka-cluster:
    image: landoop/fast-data-dev:cp3.3.0
    environment:
      ADV_HOST: 127.0.0.1
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker