version: '2'

services:

  weather-data-producer:
    image: weather-data-producer-v1
    ports:
      - "10001:8080"
    depends_on:
      - broker
    environment:
      KAFKA_BROKER: broker:9092
      KAFKA_SCHEMA_REGISTRY: http://schema-registry:8081

  weather-data-processor:
    image: weather-data-processor-v1
    ports:
      - "10002:8080"
    depends_on:
      - broker
      - weather-data-producer
      - postgres
    environment:
      KAFKA_BROKER: broker:9092
      KAFKA_SCHEMA_REGISTRY: http://schema-registry:8081

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  broker:
    image: confluentinc/cp-kafka:5.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:5.0.1
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

  kafka-rest:
    image: confluentinc/cp-kafka-rest:5.0.1
    ports:
      - "8082:8082"
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN: '*'
      KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS: GET,POST,PUT,DELETE,OPTIONS
    depends_on:
      - schema-registry
      - zookeeper
      - broker

  kafka-ui:
    image: landoop/kafka-topics-ui:latest
    ports:
      - "8000:8000"
    environment:
      KAFKA_REST_PROXY_URL: http://localhost:8082
    depends_on:
      - kafka-rest

  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: weather
    ports:
      - "5432:5432"