version: '2'

services:

  weather-data-producer:
    image: weather-data-producer-v1
    ports:
      - 10001:8080
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092 # kafka for internal docker connection, localhost for external connection
      KAFKA_SCHEMA_REGISTRY: http://kafka:8081

  weather-data-processor:
    image: weather-data-processor-v1
    ports:
      - 10002:8080
    depends_on:
      - kafka
      - weather-data-producer
      - postgres
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_SCHEMA_REGISTRY: http://kafka:8081

  kafka:
    image: landoop/fast-data-dev:cp3.3.0
    environment:
      ADV_HOST: kafka # kafka for internal docker connection, localhost for external connection
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: weather
    ports:
      - 5432:5432